# Generated by Django 4.2.1 on 2023-06-13 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Qr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serialnum", models.CharField(max_length=200, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("campo1", models.CharField(blank=True, max_length=200, null=True)),
                ("campo2", models.CharField(blank=True, max_length=200, null=True)),
                ("campo3", models.CharField(blank=True, max_length=200, null=True)),
                ("campo4", models.CharField(blank=True, max_length=200, null=True)),
                ("campo5", models.CharField(max_length=200, null=True)),
                ("campo6", models.CharField(max_length=200, null=True)),
                ("campo7", models.CharField(max_length=200, null=True)),
                (
                    "campo8_cat",
                    models.CharField(
                        choices=[("Opc_1", "Opc_1"), ("Opc_2", "Opc_2")],
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qr",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="explorador.qr",
                    ),
                ),
            ],
        ),
    ]
