# Generated by Django 4.2.1 on 2023-06-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorador", "0002_remove_qr_id_alter_qr_serialnum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qr",
            name="serialnum",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
