# Generated by Django 4.2.1 on 2023-06-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorador", "0003_alter_qr_serialnum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qr",
            old_name="campo1",
            new_name="Creador",
        ),
    ]
