# Generated by Django 4.2.1 on 2023-06-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("explorador", "0004_rename_campo1_qr_creador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carga",
            name="qr",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="explorador.qr",
            ),
        ),
    ]
