# Generated by Django 4.2.1 on 2023-06-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorador", "0005_alter_carga_qr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qr",
            name="campo2",
        ),
        migrations.AddField(
            model_name="qr",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
